# This is a basic workflow to help you get started with Actions

name: LAB1 CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: update
        run: sudo apt-get update --fix-missing
      - name: install erlang
        run: sudo apt install erlang
      - name: install rebar3
        run: sudo apt-get install rebar3
      - name: install nasm
        run: sudo apt-get install nasm
      - name: install make
        run: sudo apt-get install make
        
      # SHOW TASK 8
      - name: lint task_8_first
        run: cd 8/first && rebar3 lint
      - name: lint task_8_second
        run: cd 8/second && rebar3 lint
      - name: compile task_8_first
        run: cd 8/first && rebar3 compile
      - name: compile task_8_third
        run: cd 8/third && make

      # SHOW TASK 23
      - name: lint task_23_first
        run: cd 23/first && rebar3 lint
      - name: lint task_23_second
        run: cd 23/second && rebar3 lint
      - name: compile task_23_first
        run: cd 23/first && rebar3 compile
      - name: compile task_23_third
        run: cd 23/third && gcc main.c -o main
